### ISSUE TITLE
Can't install the plugin.

### ISSUE THREAD

**Issue by CyberSecDog** [JuanCarniglia/kbn_percent_nice_vis#1]
I get some problems installing the plugin.

~/kbn_picture_values_vis # npm run build

> kbn_picture_values_vis@1.0.0 build /root/kbn_picture_values_vis
> gulp build

[23:14:05] Requiring external module babel-register
/root/kbn_picture_values_vis/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                              ^^^^^^

**Comment by JuanCarniglia** [comment]
I think you missed the step "npm install"... did you?

**Comment by CyberSecDog** [comment]
Yes i have run the "npm install" first.
after running it agen i get.

~/kbn_picture_values_vis # npm install
npm WARN package.json kbn_picture_values_vis@1.0.0 No repository field.
npm WARN cannot run in wd kbn_picture_values_vis@1.0.0 bower install (wd=/root/kbn_picture_values_vis)

I have run the install on 3 different systems, all whit the same result.

**Comment by JuanCarniglia** [comment]
Looks like your are trying to run on "/root" and maybe that is not allowed?

Ok, give me the version numbers of:
- Kibana
- npm (npm -v)
- Babel (npm list babel)

Also, do you have a .presets.rc file in your kbn_picture_values_vis
directory?

(I have added the repository information, by the way).

Thanks

2016-06-07 14:28 GMT-03:00 tellus83 notifications@github.com:

> Yes i have run the "npm install" first.
> after running it agen i get.
> 
> ~/kbn_picture_values_vis # npm install
> npm WARN package.json kbn_picture_values_vis@1.0.0 No repository field.
> npm WARN cannot run in wd kbn_picture_values_vis@1.0.0 bower install
> (wd=/root/kbn_picture_values_vis)
> 
> I have run the install on 3 different systems, all whit the same result.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/JuanCarniglia/kbn_percent_nice_vis/issues/1#issuecomment-224353587,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOi0OytcfHljIzCHUOHxnxa7vIXFjNqJks5qJapJgaJpZM4IvaT6
> .

## 

Juan Ignacio Carniglia

**Comment by JuanCarniglia** [comment]
Any luck? How did it go?

2016-06-07 14:56 GMT-03:00 Juan Ignacio Carniglia juan.carniglia@gmail.com
:

> Looks like your are trying to run on "/root" and maybe that is not allowed?
> 
> Ok, give me the version numbers of:
> - Kibana
> - npm (npm -v)
> - Babel (npm list babel)
> 
> Also, do you have a .presets.rc file in your kbn_picture_values_vis
> directory?
> 
> (I have added the repository information, by the way).
> 
> Thanks
> 
> 2016-06-07 14:28 GMT-03:00 tellus83 notifications@github.com:
> 
> > Yes i have run the "npm install" first.
> > after running it agen i get.
> > 
> > ~/kbn_picture_values_vis # npm install
> > npm WARN package.json kbn_picture_values_vis@1.0.0 No repository field.
> > npm WARN cannot run in wd kbn_picture_values_vis@1.0.0 bower install
> > (wd=/root/kbn_picture_values_vis)
> > 
> > I have run the install on 3 different systems, all whit the same result.
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > https://github.com/JuanCarniglia/kbn_percent_nice_vis/issues/1#issuecomment-224353587,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AOi0OytcfHljIzCHUOHxnxa7vIXFjNqJks5qJapJgaJpZM4IvaT6
> > .
> 
> ## 
> 
> Juan Ignacio Carniglia

## 

Juan Ignacio Carniglia

**Comment by CyberSecDog** [comment]
No
I've tried with 3 different dockers mhart/alpine-node:4.3.0, kibana/4.5, Ubuntu/14.04.
and on 2 vanilla install off ubuntu servers 14.04

To get the npm and node.js on the ubuntu servers:

```
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
git clone https://github.com/elastic/kibana.git kibana
cd kibana

nvm install "$(cat .node-version)"
npm install

npm start (Kibana works fine)

cd ~
git clone https://github.com/JuanCarniglia/kbn_percent_nice_vis.git 
cd kbn_percent_nice_vis
npm install
npm run build
```

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/home/xxx/.nvm/versions/node/v4.4.4/bin/node" "/home/xxx/.nvm/versions/node/v4.4.4/bin/npm" "run" "build"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! kbn_percent_nice_vis@1.0.0 build: `gulp build`
npm ERR! Exit status 1

**Comment by JuanCarniglia** [comment]
I think the problem is that you have to "git clone" being in
"$kibana_home/src/plugins".

I am not sure though, but I think that you have to have the SRC files
there, in order for the plugin to work. Try just clonning into that
directory ($kibana_home/src/plugins/kbn_percent_nice_vis), and not copying
yo src/installedPlugins.

As you know, the plugins development is not exactly encouraged by elastic,
because they don't want developers and users to get to used to the current
plugins architecture, as it may change considerably in the future, so this
is way we are trying to figure things out as we go.

2016-06-12 7:34 GMT-03:00 tellus83 notifications@github.com:

> No look,
> I've tried with 3 different dockkers mhart/alpine-node:4.3.0, kibana/4.5,
> Ubuntu/14.04.
> and on 2 vanilla install off ubuntu servers 14.04
> 
> To get the npm and node.js on the ubuntu servers:
> 
> wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
> git clone https://github.com/elastic/kibana.git kibana
> cd kibana
> 
> nvm install "$(cat .node-version)"
> npm install
> 
> npm start (Kibana works fine)
> 
> cd ~
> git clone https://github.com/JuanCarniglia/kbn_percent_nice_vis.git
> cd kbn_percent_nice_vis
> npm install
> npm run build
> 
> npm ERR! Linux 4.4.0-21-generic
> npm ERR! argv "/home/xxx/.nvm/versions/node/v4.4.4/bin/node"
> "/home/xxx/.nvm/versions/node/v4.4.4/bin/npm" "run" "build"
> npm ERR! node v4.4.4
> npm ERR! npm v2.15.1
> npm ERR! code ELIFECYCLE
> npm ERR! kbn_percent_nice_vis@1.0.0 build: gulp build
> npm ERR! Exit status 1
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/JuanCarniglia/kbn_percent_nice_vis/issues/1#issuecomment-225425461,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOi0O2vP8AZLamOXCzZ1xooq3kbX_Vmkks5qK-DKgaJpZM4IvaT6
> .

## 

Juan Ignacio Carniglia

**Comment by CyberSecDog** [comment]
I create a .babelrc file:

```
{
"presets": ["es2015"]
}

```

And :

```
 npm install  gulp@3.9.0
 npm install -g  gulp@3.9.0
```

This works to build the plugin.
I have to do the same in the test environment to confirm it works.

**Comment by CyberSecDog** [comment]
After installing it inn the InstallPlugin folder i get this from Kibana plugin: when i try to install a other plugin that works fine if i remove the percent plugin. 

> Plugin installation was unsuccessful due to error "Cannot read property 'error' of undefined"

And Kibana do not start.

**Comment by CyberSecDog** [comment]
@JuanCarniglia can you help. I really want to use all your plugins. But my skill level is not there yet.
I got it to build. But the plugin do not work. i have tried all of your plugins and all wit the same problem. It has to be my setup but i have tried many different setups and distros.

**Comment by JuanCarniglia** [comment]
Have you tried putting the plugins in the src/plugins/[plugin_name] folder,
instead of actually installing them?

2016-06-13 15:16 GMT-03:00 tellus83 notifications@github.com:

> @JuanCarniglia https://github.com/JuanCarniglia can you help. I really
> want to use all your plugins. But my skill level is not there yet.
> I got it to build. But the plugin do not work. i have tried all of your
> plugins and all wit the same problem. It has to be my setup but i have
> tried many different setups and distros.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/JuanCarniglia/kbn_percent_nice_vis/issues/1#issuecomment-225664190,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOi0O4d_cqY9BBJj1arop0qk2J3d6maGks5qLZ6TgaJpZM4IvaT6
> .

## 

Juan Ignacio Carniglia

**Comment by CyberSecDog** [comment]
Yes, if i put the plugin in the scr/plugins folder and restart Kibana i get:

`{"type":"log","@timestamp":"2016-06-13T20:35:26+00:00","tags":["fatal"],"pid":12,"level":"fatal","message":"EACCES: permission denied, open '/opt/kibana/optimize/bundles/sense.entry.js'","error":{"message":"EACCES: permission denied, open '/opt/kibana/optimize/bundles/sense.entry.js'","name":"Error","stack":"Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/sense.entry.js'\n    at Error (native)","code":"EACCES"}}
FATAL { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/sense.entry.js']
  cause:
   { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/sense.entry.js']
     errno: -13,
     code: 'EACCES',
     syscall: 'open',
     path: '/opt/kibana/optimize/bundles/sense.entry.js' },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/kibana/optimize/bundles/sense.entry.js' }
`
delete the scr/plugins/"plugin" folder all run fine.

**Comment by JuanCarniglia** [comment]
Run it with sudo?

**Comment by CyberSecDog** [comment]
Yes.I changed the folder owner and permissions to match the others plugins.  i have tried with sudo, No change.
