### ISSUE TITLE
Port for Kibana 5

### ISSUE THREAD

**Issue by ulir** [JuanCarniglia/kbn_percent_nice_vis#3]
Hi Juan,

do you have plans to port this plugins to Kibana 5?
Any idea how much of an effort this would be?

Best,
Uli

**Comment by vram001** [comment]
+1

**Comment by neilc2016** [comment]
I have same issue.  Any eta on v5 port?

**Comment by JuanCarniglia** [comment]
Ok, done. Please someone clone and test this. It's working on 6.0.0-alpha1, so it should also work on 5.x.

(The new code is in the releases folder)

(There may be an issue with the images, due to the inclusion of basePath).

Please let me know how it goes.

Thanks!

**Comment by neilc2016** [comment]
I'm getting module not found errors in the Kibana 5.2 installation.  Is there something else that needs to be installed first?

Module not found: Error: Cannot resolve 'file' or 'directory' /vapews/devops/tools/kibana-5.2.1-SNAPSHOT-linux-x86_64/src/ui/public/Vis/Schemas in /vapews/devops/tools/kibana-5.2.1-SNAPSHOT-linux-x86_64/plugins/kbn_percent_nice_vis/public\n  

Module not found: Error: Cannot resolve 'file' or 'directory' /vapews/devops/tools/kibana-5.2.1-SNAPSHOT-linux-x86_64/src/ui/public/template_vis_type/TemplateVisType in /vapews/devops/tools/kibana-5.2.1-SNAPSHOT-linux-x86_64/plugins/kbn_percent_nice_vis/public\n_

**Comment by JuanCarniglia** [comment]
Please pull again and try it out. There were some changes that just weren't there.

Sorry. Let me know if it works please.

**Comment by neilc2016** [comment]
Thanks Juan, that cleared up the installation issues.  Will check out the functionality and get back to you.

**Comment by neilc2016** [comment]
Plugin working fine in Kibana v5.  The visualizations and dashboards showing percent images just as Kibana v4.

**Comment by vram001** [comment]
Plugin working for V5, 
Thank you

**Comment by JuanCarniglia** [comment]
Thanks you all!
